### ISSUE TITLE
Could you please move the DAO implementations to a different JAR file?

### ISSUE THREAD

**Issue by mattes3** [yoomoney-tech/db-queue#12]
Hi,

I'd like to use this package but my environment uses a different DB access technology, without Spring.

Could you please move the DAOs to a different, Spring-specific DAO JAR? That way, I could write my own implementation of the DAO interface, without any dependency on Spring. This would also require that the factory class is not part of the DAO interface any more.

Cheers
Matthias

**Comment by f0y** [comment]
Hi,

What kind of DB access technology do you use?

**Comment by mattes3** [comment]
Two technologies:

- JDBI https://github.com/jdbi/jdbi
- JPA with Hibernate

JDBI for tabular access, JPA for object-based access

**Comment by f0y** [comment]
It is not an easy task. We also use Spring transactions internally https://github.com/yoomoney-tech/db-queue/blob/master/src/main/java/ru/yoomoney/tech/dbqueue/internal/runner/QueueRunnerInTransaction.java#L47. How do you plan to deal with it?

**Comment by mattes3** [comment]
Oh, yes, I see! I forgot to think about transactions. So the DB access interface would not only need to have DAO methods but transaction methods as well. Let me think about it.

**Comment by mattes3** [comment]
I've had a look at the code. I offer you to refactor it myself. Afterwards, maybe I can provide a PR. Would you be interested? In that case, I will need to know how to test it with a postgres database.

**Comment by f0y** [comment]
Yes, I'm interested. You can make a draft so I'll be able to get your idea. The final solution I'll implement by myself.

**Comment by mattes3** [comment]
Hey Oleg, I worked on this for one day and committed it here: https://github.com/mattes3/db-queue

However, I stopped because it is simply too much work. The assumption that a QueueShard contains a JDBC template is at too many places in the source code.

Maybe you can see my interface called "Database" and the derived class `SpringJdbcBasedDatabase` to get an idea into which direction I was trying to go.

I have to stop because I don't have so much time to really make it work.

Sorry!
Matthias

**Comment by f0y** [comment]
Thank you, Matthias. I understood the idea of the `Database` interface. Give me some time and I'll move out spring to another module.

**Comment by f0y** [comment]
Fixed in https://github.com/yoomoney-tech/db-queue/pull/14. 

Matthias, you can use `ru.yoomoney.tech:db-queue-core:12.0.0` to implement database access via desired technologies.
