### ISSUE TITLE
Does the library work in clustered mode?

### ISSUE THREAD

**Issue by isaric** [yoomoney-tech/db-queue#16]
Hi, sorry for opening an issue but I didn't see another way to contact the maintainers.

I would like to use this lib as part of a larger monolith that can also operate in clustered mode.

If that is the case, can the library  be configured to operate consistently across all nodes of the cluster
so that each node can both insert jobs and work on jobs without conflict?

Every node of the cluster is hooked up to the same SQL db.

**Comment by f0y** [comment]
Hi! We have at least 4 instances of each microservice. These 4 instances use the same database. Db-queue runs on all instances of a microservice, so we always use db-queue in clustered mode. Make sure your database use read committed transaction isolation level and everything will be fine.

**Comment by isaric** [comment]
Thanks for the quick reply. I will give the lib a try. Closing the issue.
