### ISSUE TITLE
Dbqueue tries to catch Error

### ISSUE THREAD

**Issue by evgeniy-storozhenko** [yoomoney-tech/db-queue#8]
Is there any reason why _QueueLoop_ tries to catch _Throwable_ that includes critical Errors such as OOM? It just eats them.

**Comment by evgeniy-storozhenko** [comment]
https://github.com/yoomoney-tech/db-queue/pull/9

**Comment by f0y** [comment]
Thank you for your contribution. Do you have some issues with your production code?
